#!/bin/bash
export PATH=/usr/lib/ccache:$PATH

RUN_TESTS=$1
PACKAGES=${*:2}

echo Checking whether we should run the tests...
if $RUN_TESTS; then
  echo "Will first build $PACKAGES and then run tests."
else
  echo "Will only build $PACKAGES and skip tests."
fi


cd $WORKSPACE
export ROS_WS=$WORKSPACE/ros_ws
rm -rf $ROS_WS
mkdir -p $ROS_WS
rosws init $ROS_WS /opt/ros/hydro
for package in $(find ./* -type d)
do
  if [ -a "$package/manifest.xml" ]
    then
    echo "$package is a ros package."
    cd $ROS_WS
    if [ $package != "ros_ws" ]; then
      rosws set ../$package -y
    fi
  fi
  cd $WORKSPACE
done
source $ROS_WS/setup.bash
source $ROS_WS/setup.sh
# We use ccache, so already build files will take little time to rebuild, 
# so pre-clean is fine to be sure there are no stale files.
VERBOSE=1 rosmake ${PACKAGES} -V --pre-clean

# Die if rosmake fails.
ret_code=$?
if [ $ret_code != 0 ]; then
  exit $ret_code
fi

if $RUN_TESTS; then
  # Clear out results from the requested packages.
  TEST_RESULTS_FOLDER=$HOME/.ros/test_results
  for package in ${PACKAGES}
  do
      echo "Clearing test results in $TEST_RESULTS_FOLDER/$package ..."
      rm -rf $TEST_RESULTS_FOLDER/$package
  done
  # Run the tests. Don't fail if the tests fail, we will parse their results later.
  rosmake ${PACKAGES} -Vk --test-only

  # Clear / Create a directory in the workspace where we can store the test results.
  TEST_RESULTS_DEST=$WORKSPACE/test_results/
  rm -rf $TEST_RESULTS_DEST
  mkdir -p $TEST_RESULTS_DEST
  for package in ${PACKAGES}
  do
      # Copy all test results from the currently build packages to the workspace folder.
      echo "Copying test results from $TEST_RESULTS_FOLDER/$package to $TEST_RESULTS_DEST..."
      mkdir -p $TEST_RESULTS_DEST/$package/
      # Only copy rosunit xml files.
      cp -r $TEST_RESULTS_FOLDER/$package/rosunit* $TEST_RESULTS_DEST/$package/ || true
  done
fi
cd $ROS_WS
rm -rf `find . -type d -name build` || true
