#!/bin/bash
cd $WORKSPACE
export ROS_WS=$WORKSPACE/ros_ws
rm -rf $ROS_WS
mkdir $ROS_WS
rosws init $ROS_WS /opt/ros/hydro
for package in $(find ./* -type d)
do
  if [ -a "$package/manifest.xml" ]
    then
    echo "$package is a ros package."
    cd $ROS_WS
    if [ $package != "ros_ws" ]; then
      rosws set ../$package -y
    fi
  fi
  cd $WORKSPACE
done
source $ROS_WS/setup.bash
source $ROS_WS/setup.sh
# We use ccache, so already build files will take little time.
VERBOSE=1 rosmake $@ -V --pre-clean
