#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "PACKAGES:" $@

cd $WORKSPACE/src
if [ -e "manifest.xml" ] || [ -e "stack.xml" ]; then
  $DIR/rosmake_repo $@
else
  cd $WORKSPACE
  $DIR/catkin_make_repo $@
fi
